# Generated by Django 5.2 on 2025-04-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('curso', models.CharField(max_length=25)),
                ('nota_final', models.CharField(max_length=10)),
            ],
        ),
    ]
